/**
 * Mock 演示数据 — 供 Demo 部署时使用
 * 真实数据结构，全部脱敏（无真实 URL / Cookie 信息）
 */
import type { SearchResponse, ChatResponse, ParsedRequirement } from './types';

export const MOCK_REQUIREMENT: ParsedRequirement = {
  destination: {
    city: '广州',
    district: '天河',
    landmark: '珠江新城',
    address: '广州市天河区珠江新城',
    geo: { lng: 113.3233, lat: 23.1201 },
  },
  commute: { max_minutes: 40, modes: ['transit', 'riding', 'walking'], maps: ['amap'] },
  rental_type: { include: ['整租'], exclude: ['合租', '地下室'] },
  price: { base_rent_max: 4000, base_rent_min: null, total_cost_max: null, total_cost_min: null },
  soft_preferences: ['近地铁', '电梯'],
  hard_excludes: ['城中村'],
  raw_text: '广州天河，通勤珠江新城，3500以内整租，近地铁',
};

export const MOCK_SEARCH_RESPONSE: SearchResponse = {
  session_id: 'demo-session-001',
  total_crawled: 186,
  total_filtered: 23,
  total_pages: 3,
  current_page: 1,
  message: '演示模式：展示真实数据结构，实际部署后抓取真实房源',
  has_commute: true,
  counts_by_platform: { all: 23, lianjia: 9, beike: 8, anjuke: 4, wuba: 2 },
  geo_filter_stats: { total: 186, geocoded: 174, geocode_failed: 12, within_radius: 23, out_of_radius: 151 },
  commute_source_stats: { offline: 15, amap: 8, total: 23, precise: 8 },
  radius_km: 10,
  geocode_precision: 'exact',
  geocode_warning: '',
  dest_label: '珠江新城（天河区）',
  recommendations: [
    {
      listing: {
        id: 'demo-001',
        platform: 'lianjia',
        platform_id: 'lj001',
        url: 'https://gz.lianjia.com/zufang/demo',
        title: '珠江新城 | 天河某花园 精装两房 近地铁5号线',
        price_base: 3200,
        price_total: 3200,
        area: 68,
        layout: '2室1厅',
        floor: '中楼层/共26层',
        has_elevator: true,
        orientation: '南',
        rental_type_tag: '整租',
        address: '广州市天河区珠江新城附近',
        community: '天河某花园',
        geo_lng: 113.3289,
        geo_lat: 23.1198,
        images: [
          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop',
          'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=400&h=300&fit=crop',
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
        ],
        raw_data: {},
        confidence_score: 0.92,
        missing_fields: [],
      },
      cost: {
        base_rent: 3200, property_fee: 136, water: 30, electricity: 80,
        gas: 20, internet: 60, agency_fee_monthly: 133, deposit_cost: 8,
        other: 0, total: 3667,
        notes: {
          property_fee: '按 2元/㎡/月 × 68㎡',
          electricity: '按默认 100度/月 × 0.8元/度',
          agency_fee_monthly: '半月租金 ÷ 12个月摊销',
        },
      },
      commute: {
        listing_id: 'demo-001',
        destination_address: '珠江新城',
        best_duration_min: 18,
        avg_transit_min: 22,
        nearest_metro: '珠江新城站',
        metro_walk_min: 8,
        results: [
          { map_provider: 'amap', mode: 'transit', duration_min: 22, distance_km: 3.2, direction: 'home_to_work', nearest_metro: '珠江新城站', metro_walk_min: 8, metro_distance_m: 650, transfers: 0 },
          { map_provider: 'amap', mode: 'riding', duration_min: 18, distance_km: 2.8, direction: 'home_to_work', nearest_metro: null, metro_walk_min: null, metro_distance_m: null, transfers: null },
          { map_provider: 'amap', mode: 'walking', duration_min: 38, distance_km: 2.8, direction: 'home_to_work', nearest_metro: null, metro_walk_min: null, metro_distance_m: null, transfers: null },
        ],
      },
      score: 0.91,
      rank: 1,
      reason: '价格合理，精装电梯，骑行18分钟可达',
      flags: ['近地铁', '精装修', '电梯'],
      ai_review: {
        score: 8.5,
        summary: '性价比不错的天河两房，骑行通勤很方便，精装修拎包入住',
        pros: ['骑行18分钟直达珠江新城', '精装修拎包入住', '有电梯高楼层', '近地铁5号线步行8分钟'],
        cons: ['中介费需确认', '缺少阳台'],
        tags: ['精装修', '近地铁', '电梯', '骑行友好'],
        generated_at: '2026-05-20T12:00:00',
        model: 'deepseek-chat',
      },
    },
    {
      listing: {
        id: 'demo-002',
        platform: 'beike',
        platform_id: 'bk002',
        url: 'https://gz.ke.com/zufang/demo',
        title: '天河北 | 岗顶某小区 一房一厅 采光好',
        price_base: 2600,
        price_total: 2600,
        area: 45,
        layout: '1室1厅',
        floor: '高楼层/共33层',
        has_elevator: true,
        orientation: '东南',
        rental_type_tag: '整租',
        address: '广州市天河区天河北路附近',
        community: '岗顶某小区',
        geo_lng: 113.3401,
        geo_lat: 23.1312,
        images: [
          'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&h=300&fit=crop',
          'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=400&h=300&fit=crop',
        ],
        raw_data: {},
        confidence_score: 0.88,
        missing_fields: [],
      },
      cost: {
        base_rent: 2600, property_fee: 90, water: 30, electricity: 80,
        gas: 20, internet: 60, agency_fee_monthly: 108, deposit_cost: 6,
        other: 0, total: 2994,
        notes: { property_fee: '按 2元/㎡/月 × 45㎡' },
      },
      commute: {
        listing_id: 'demo-002',
        destination_address: '珠江新城',
        best_duration_min: 25,
        avg_transit_min: 28,
        nearest_metro: '岗顶站',
        metro_walk_min: 5,
        results: [
          { map_provider: 'amap', mode: 'transit', duration_min: 28, distance_km: 5.1, direction: 'home_to_work', nearest_metro: '岗顶站', metro_walk_min: 5, metro_distance_m: 380, transfers: 1 },
          { map_provider: 'amap', mode: 'riding', duration_min: 25, distance_km: 4.6, direction: 'home_to_work', nearest_metro: null, metro_walk_min: null, metro_distance_m: null, transfers: null },
        ],
      },
      score: 0.85,
      rank: 2,
      reason: '价格经济，一人居住空间够用',
      flags: ['近地铁', '电梯', '采光好'],
      ai_review: null,
    },
    {
      listing: {
        id: 'demo-003',
        platform: 'anjuke',
        platform_id: 'aj003',
        url: 'https://gz.anjuke.com/zu/demo',
        title: '猎德 | 花城汇附近精装三房 适合拼租或家庭',
        price_base: 5800,
        price_total: 5800,
        area: 112,
        layout: '3室2厅',
        floor: '低楼层/共18层',
        has_elevator: true,
        orientation: '南北通透',
        rental_type_tag: '整租',
        address: '广州市天河区猎德大道附近',
        community: '花城汇附近某大院',
        geo_lng: 113.3198,
        geo_lat: 23.1145,
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
          'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=400&h=300&fit=crop',
          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
        ],
        raw_data: {},
        confidence_score: 0.79,
        missing_fields: [],
      },
      cost: {
        base_rent: 5800, property_fee: 224, water: 45, electricity: 120,
        gas: 30, internet: 60, agency_fee_monthly: 242, deposit_cost: 14,
        other: 0, total: 6535,
        notes: { property_fee: '按 2元/㎡/月 × 112㎡' },
      },
      commute: {
        listing_id: 'demo-003',
        destination_address: '珠江新城',
        best_duration_min: 12,
        avg_transit_min: 15,
        nearest_metro: '猎德站',
        metro_walk_min: 6,
        results: [
          { map_provider: 'amap', mode: 'transit', duration_min: 15, distance_km: 1.8, direction: 'home_to_work', nearest_metro: '猎德站', metro_walk_min: 6, metro_distance_m: 480, transfers: 0 },
          { map_provider: 'amap', mode: 'riding', duration_min: 12, distance_km: 1.6, direction: 'home_to_work', nearest_metro: null, metro_walk_min: null, metro_distance_m: null, transfers: null },
          { map_provider: 'amap', mode: 'walking', duration_min: 22, distance_km: 1.6, direction: 'home_to_work', nearest_metro: null, metro_walk_min: null, metro_distance_m: null, transfers: null },
        ],
      },
      score: 0.78,
      rank: 3,
      reason: '离目的地最近，但预算偏高',
      flags: ['近地铁', '南北通透', '大三房'],
      ai_review: null,
    },
    {
      listing: {
        id: 'demo-004',
        platform: 'lianjia',
        platform_id: 'lj004',
        url: 'https://gz.lianjia.com/zufang/demo4',
        title: '五山 | 华南理工附近 精装一房 安静宜居',
        price_base: 2200,
        price_total: 2200,
        area: 38,
        layout: '1室1厅',
        floor: '中楼层/共12层',
        has_elevator: true,
        orientation: '南',
        rental_type_tag: '整租',
        address: '广州市天河区五山路附近',
        community: '五山某苑',
        geo_lng: 113.3512,
        geo_lat: 23.1389,
        images: [
          'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=400&h=300&fit=crop',
        ],
        raw_data: {},
        confidence_score: 0.83,
        missing_fields: ['通勤未测算（离线估算）'],
      },
      cost: {
        base_rent: 2200, property_fee: 76, water: 30, electricity: 80,
        gas: 20, internet: 60, agency_fee_monthly: 92, deposit_cost: 5,
        other: 0, total: 2563,
        notes: {},
      },
      commute: {
        listing_id: 'demo-004',
        destination_address: '珠江新城',
        best_duration_min: 33,
        avg_transit_min: 38,
        nearest_metro: '五山站',
        metro_walk_min: 12,
        results: [
          { map_provider: 'stable_baseline', mode: 'transit', duration_min: 38, distance_km: 6.8, direction: 'home_to_work', nearest_metro: '五山站', metro_walk_min: 12, metro_distance_m: 950, transfers: 1 },
          { map_provider: 'stable_baseline', mode: 'riding', duration_min: 33, distance_km: 5.9, direction: 'home_to_work', nearest_metro: null, metro_walk_min: null, metro_distance_m: null, transfers: null },
        ],
      },
      score: 0.74,
      rank: 4,
      reason: '价格最低，通勤略长但在接受范围内',
      flags: ['价格优势', '安静'],
      ai_review: null,
    },
    {
      listing: {
        id: 'demo-005',
        platform: 'beike',
        platform_id: 'bk005',
        url: 'https://gz.ke.com/zufang/demo5',
        title: '天河公园 | 新装修两房 小区绿化好 物业正规',
        price_base: 3600,
        price_total: 3600,
        area: 72,
        layout: '2室1厅',
        floor: '高楼层/共28层',
        has_elevator: true,
        orientation: '南',
        rental_type_tag: '整租',
        address: '广州市天河区天河公园附近',
        community: '天河公园某苑',
        geo_lng: 113.3356,
        geo_lat: 23.1267,
        images: [
          'https://images.unsplash.com/photo-1571508601891-ca5e7a713859?w=400&h=300&fit=crop',
          'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=400&h=300&fit=crop',
        ],
        raw_data: {},
        confidence_score: 0.86,
        missing_fields: [],
      },
      cost: {
        base_rent: 3600, property_fee: 144, water: 30, electricity: 80,
        gas: 20, internet: 60, agency_fee_monthly: 150, deposit_cost: 9,
        other: 0, total: 4093,
        notes: {},
      },
      commute: {
        listing_id: 'demo-005',
        destination_address: '珠江新城',
        best_duration_min: 20,
        avg_transit_min: 24,
        nearest_metro: '天河公园站',
        metro_walk_min: 7,
        results: [
          { map_provider: 'amap', mode: 'transit', duration_min: 24, distance_km: 3.9, direction: 'home_to_work', nearest_metro: '天河公园站', metro_walk_min: 7, metro_distance_m: 560, transfers: 0 },
          { map_provider: 'amap', mode: 'riding', duration_min: 20, distance_km: 3.5, direction: 'home_to_work', nearest_metro: null, metro_walk_min: null, metro_distance_m: null, transfers: null },
        ],
      },
      score: 0.82,
      rank: 5,
      reason: '新装修，绿化好，通勤20分钟',
      flags: ['新装修', '绿化好', '近地铁'],
      ai_review: null,
    },
  ],
};

export const MOCK_CHAT_REPLIES: Record<string, string> = {
  default: '收到！我来帮你在广州天河区寻找房源，通勤珠江新城，预算3500以内整租。正在为你匹配合适的房源，请稍候……',
  price: '好的，已将预算调整为你指定的范围，重新为你筛选中……',
  commute: '明白，已把通勤时间上限更新，优先展示距离更近的房源……',
  reset: '好的，已重置搜索条件，请重新告诉我你的需求：目标城市、通勤目的地和预算范围。',
};
